import type { MenuItem } from "./types";

export const menuItems: MenuItem[] = [
  {
    id: "winter-melon-pork-rib-soup",
    name: "冬瓜薏米排骨湯",
    description: "冬瓜、薏米與排骨慢火細熬，湯色清潤，適合日常調養。",
    price: 180,
    category: "seasonalSoup",
    imageUrl: "/images/four-season-ginseng-soup.jpg",
    available: true,
  },
  {
    id: "lotus-root-peanut-soup",
    name: "蓮藕花生章魚湯",
    description: "蓮藕、花生與章魚乾同煲，香氣溫厚，口感甘潤紮實。",
    price: 210,
    category: "seasonalSoup",
    imageUrl: "/images/lotus-root-pork-soup.jpg",
    available: true,
  },
  {
    id: "silkie-chicken-herbal-soup",
    name: "黨參北耆烏雞燉湯",
    description: "烏雞佐黨參、北耆與紅棗慢燉，湯味醇和，補而不燥。",
    price: 260,
    category: "herbalSoup",
    imageUrl: "/images/herbal-black-chicken-soup.jpg",
    available: true,
  },
  {
    id: "cordyceps-flower-chicken-soup",
    name: "蟲草花淮山雞湯",
    description: "蟲草花、淮山與雞肉細火燉煮，香甜清雅，適合養氣暖身。",
    price: 240,
    category: "herbalSoup",
    imageUrl: "/images/cordyceps-chicken-soup.jpg",
    available: true,
  },
  {
    id: "snow-fungus-papaya-dessert",
    name: "雪耳木瓜燉糖水",
    description: "雪耳與木瓜燉至柔滑，甜度溫和，潤喉養顏。",
    price: 120,
    category: "dessertSoup",
    imageUrl: "/images/almond-walnut-dessert.jpg",
    available: true,
  },
  {
    id: "black-sesame-walnut-dessert",
    name: "黑芝麻核桃糊",
    description: "黑芝麻與核桃細磨熬成濃滑糖水，香氣厚實，溫潤順口。",
    price: 130,
    category: "dessertSoup",
    imageUrl: "/images/red-bean-lotus-dessert.jpg",
    available: true,
  },
  {
    id: "red-date-longan-tea",
    name: "紅棗桂圓養生茶",
    description: "紅棗、桂圓與枸杞溫泡，茶湯甘甜，適合午後慢飲。",
    price: 90,
    category: "teaDrink",
    imageUrl: "/images/chrysanthemum-tea.jpg",
    available: true,
  },
  {
    id: "chrysanthemum-goji-tea",
    name: "菊花枸杞清潤茶",
    description: "菊花與枸杞清泡，入口淡雅回甘，帶來清爽舒緩的茶韻。",
    price: 85,
    category: "teaDrink",
    imageUrl: "/images/luo-han-guo-tea.jpg",
    available: true,
  },
];
